### PR TITLE
Add workflow that automatically updates documents

### PR DESCRIPTION
**Pull request by Kremtastic**
Add a workflow that automates the process of fetching and updating documents (from the admin-repo) for the website.

### CODE REVIEW

**Comment by mathiash98** [comment]
This looks promising! I have not taken a deep look yet

**Comment by Kremtastic** [comment]
I haven't truly tested if this works yet. It seemed like it had to be added to the main branch first for the workflow to actually be able to be triggered.

**Comment by mathiash98** [comment]
> I haven't truly tested if this works yet. It seemed like it had to be added to the main branch first for the workflow to actually be able to be triggered.

Yes that is correct, this workflow will then copy all dagsordener from admin repo, convert to toml and make them available in fribyte.no.

I'm a bit worried that a public git repo will have access to stuff in a private git repo, hmmm. Maybe we should add this github action in the admin repo instead and push files to fribyte.no repo.
- This will make the changes automatic as well and not require us to trigger the Github Action in fribyte.no every time we want new data

**Comment by polsevev** [comment]
I would assume setting this up as a separate folder on the host system of fribyte.no, then pushing files from an action in the admin repo is a more secure way of performing this. As having an action on PR that triggers a PR from a private repo is something i am not comfortable with.

**Pull request closed without merging**
