### PR TITLE
added Velferdstinget Vest logo på footeren

### PR DESCRIPTION
**Pull request by nheek**
Skjermbilde 2024-04-16 kl  19 06 57
Skjermbilde 2024-04-16 kl  19 06 49

### CODE REVIEW

**Review by SindreKjelsrud — COMMENTED** [review]
Looks very nice, just wondering if we should have their logo in red on lightmode? :thinking:

**Comment by nheek** [comment]
> Looks very nice, just wondering if we should have their logo in red on lightmode? 🤔 But great job!!

Oh yeah forgot to link. Here's the guideline they have

https://drive.google.com/file/d/153-ywFRsCM0vCUIKVfCYpriaFeVdsQBI/view

According to that, only use the blue one as a default. Only resort to the red one if for some reason the blue one is "not possible". Also, use the red for CTAs, and I don't think ours count as one.

**Comment by nheek** [comment]
But I agree with the red actually since it aligns with friByte's color better so I'm not against it. What do we think?

**Comment by nheek** [comment]
Skjermbilde 2024-04-16 kl  19 21 17

**Comment by skivdal** [comment]
Maybe black?

**Comment by nheek** [comment]
> Maybe black?

Yeah but it says that hels til saksdokumenter.

**Comment by skivdal** [comment]
Idk, their red is different to ours, but this is not too important, just do what you think looks the best :)
On another note, it should probably say "Støttet av", not "Sponsor" imo, they're not a sponsor

**Comment by nheek** [comment]
> Idk, their red is different to ours, but this is not too important, just do what you think looks the best :) On another note, it should probably say "Støttet av", not "Sponsor" imo, they're not a sponsor

Yeah I was originally gonna go with "Støttet av" but for some reason I didn't XD

**Comment by nheek** [comment]
Changed it. All good? 🙏

**Comment by skivdal** [comment]
Yes, nice!

**Review by skivdal — APPROVED** [review]

**Comment by nheek** [comment]
Thanks! ❤️

**Pull request merged**
